image: python:3.9.5-buster

pages:
  stage: deploy
  script:
  - git submodule update --remote --recursive
  - apt-get update && apt-get -y install openmpi-bin openmpi-common libopenmpi-dev libboost-all-dev build-essential
  - pip install --upgrade pip wheel && pip install -r requirements.txt -r requirements-dev.txt && python setup.py develop
  - sphinx-build -b html doc/ public
  artifacts:
    paths:
    - public
  only:
  - master
