repos:
-   repo: https://github.com/python/black
    rev: 24.3.0
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
    - id: blacken-docs
      additional_dependencies:
        - black==24.3.0
