name: Python package build

on: [push]
#  release:
#    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache python environment
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('pyproject.toml') }}
      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.7.1-manylinux2014_x86_64
        with:
          python-versions: 'cp39-cp39'
#          build-requirements: 'cython numpy'
          system-packages: 'boost-devel gcc gcc-c++ make'
#          pre-build-command: 'sh pre-build-script.sh'
#          package-path: 'my_project'
#          pip-wheel-args: '-w ./dist --no-deps'
#      - name: Publish wheels to PyPI
#        env:
#          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#        run: |
#          twine upload dist/*-manylinux*.whl
