# Build RidePy docs
name: docs

on:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Cache python environment
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('pyproject.toml') }}
      - name: Install system dependencies using apt
        run: |
          sudo apt-get update && sudo apt-get -y install libboost-all-dev build-essential
      - name: Install Dependencies
        run: |
          pip install -U pip 
          pip install .[doc]
      - name: Build doc
        run: sphinx-build -b dirhtml ./doc/ ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
