name: wheel

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Cache python environment
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('pyproject.toml') }}
      - name: Install dependencies
        run: |
          pip install -U pip 
          pip install -U twine
      - name: Build manylinux Python wheel
        uses: RalfG/python-wheels-manylinux-build@v0.7.1-manylinux2014_x86_64
        with:
          python-versions: 'cp39-cp39'
#          build-requirements: 'cython numpy'
          system-packages: 'boost-devel gcc gcc-c++ make'
#          pre-build-command: 'sh pre-build-script.sh'
#          package-path: 'my_project'
#          pip-wheel-args: '-w ./dist --no-deps'
      - uses: actions/upload-artifact@v4
        with:
          name: wheel-manylinux
          path: dist/*-manylinux*.whl
