name: pypi

on:
  release:
    types: [published]

concurrency:
  group: "pypi"
  cancel-in-progress: false

jobs:
  sdist:
    uses: ./.github/workflows/build-sdist.yml
  wheel:
    uses: ./.github/workflows/build-wheel.yml
  test:
    uses: ./.github/workflows/python-testing.yml
  deploy-doc:
    uses: ./.github/workflows/deploy-doc.yml
  deploy:
    runs-on: ubuntu-latest
    environment: pypi
    needs: [sdist, wheel, test, deploy-doc]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sdist
          path: dist
      - uses: actions/download-artifact@v3
        with:
          name: wheel-manylinux
          path: dist
      - name: Show what is being published
        run: ls -lah
        working-directory: dist
      - name: Publish package to PyPI
        if: startsWith(github.ref, 'refs/tags/v') # just to be safe
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
