
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.2

    - name: Cache python environment
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}

    - name: Install system dependencies using apt
      run: |
        sudo apt-get update && sudo apt-get -y install openmpi-bin openmpi-common libopenmpi-dev libboost-all-dev build-essential


    - name: Install Dependencies
      # Somehow the tests fail if we do python setup.py install
      #run: pip install --upgrade pip wheel && pip install -r requirements.txt -r requirements-dev.txt && python setup.py develop
      run: pip install pytest cython==3.0a6 && python setup.py develop


    - name: Test with pytest
      run: |
        pytest -p no:cacheprovider -vvv --junitxml=test-junit-reports/result.xml

    - name: Test OpenMPI stuff
      run: |
        mpirun --host localhost:4 -n 4  python -m mpi4py.futures test/mpi_futures_fleet_state_test.py

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.9
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Unit Test Results
        files: test-junit-reports/*.xml
        report_individual_runs: true
        deduplicate_classes_by_file_name: false
