
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install system dependencies using apt
      run: |
        sudo apt-get install openmpi-bin openmpi-common libopenmpi-dev

    - name: Create venv
      run: |
        python3.8 -m venv .venv


    - name: Install Dependencies
      # Somehow the test fail if we do python setup.py install
      run: pip install -r requirements.txt -r requirements-dev.txt && python setup.py develop


    - name: Test with pytest
      run: |
        pytest -vvv --junitxml=test-junit-reports/result.xml
        
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Unit Test Results
        files: test-junit-reports/*.xml
        report_individual_runs: true
        deduplicate_classes_by_file_name: false
