
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install system dependencies using apt
      run: |
        sudo apt-get update && sudo apt-get install openmpi-bin openmpi-common libopenmpi-dev libboost-all-dev

    - name: Install Dependencies
      # Somehow the tests fail if we do python setup.py install
      run: pip install --upgrade pip wheel && pip install -r requirements.txt -r requirements-dev.txt && python setup.py develop

    - name: Test with pytest
      run: |
        pytest -vvv --junitxml=test-junit-reports/result.xml --cov=thesimulator test

    - name: Generate coverage badge
      run: coverage-badge -fo ${{ github.workspace }}/.coverage.svg

    - name: Upload coverage badge
      uses: actions/upload-artifact@v2
      with:
        name: coverage-badge
        path: ${{ github.workspace }}/.coverage.svg

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.9
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Unit Test Results
        files: test-junit-reports/*.xml
        report_individual_runs: true
        deduplicate_classes_by_file_name: false
